include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unnecessary_underscores: ignore
    use_build_context_synchronously: ignore

linter:
  rules:
    avoid_print: false
