import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/utils/currency_formatter.dart';
import '../../../../data/models/budget_strategy.dart';
import '../../../../providers/budget_provider.dart';
import '../../../../providers/transaction_provider.dart';

class BudgetStrategyCard extends ConsumerWidget {
  final String currency;

  const BudgetStrategyCard({super.key, required this.currency});

  void _showAutoGenerateDialog(BuildContext context, WidgetRef ref, double initialIncome) {
    final controller = TextEditingController(
      text: initialIncome > 0 ? initialIncome.toStringAsFixed(0) : '3000',
    );

    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Row(
          children: [
            const Icon(Icons.auto_awesome_rounded, color: AppColors.primary),
            const SizedBox(width: 8),
            const Expanded(child: Text('Auto-Generate Budgets')),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Enter your total monthly income or spending pool. Budgets will be proportionally distributed across your expense categories matching the active strategy.',
              style: TextStyle(fontSize: 13, color: Colors.grey),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: controller,
              keyboardType: const TextInputType.numberWithOptions(decimal: true),
              autofocus: true,
              decoration: InputDecoration(
                labelText: 'Monthly Pool / Income Amount',
                prefixText: '$currency ',
                border: const OutlineInputBorder(),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel'),
          ),
          ElevatedButton.icon(
            onPressed: () async {
              final amt = double.tryParse(controller.text.trim()) ?? 0.0;
              if (amt > 0) {
                final count = await ref
                    .read(budgetProvider.notifier)
                    .autoGenerateBudgetsFromStrategy(monthlyPoolAmount: amt);
                if (context.mounted) {
                  Navigator.pop(ctx);
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text('Auto-generated $count category budgets from active strategy!'),
                      backgroundColor: AppColors.asset,
                    ),
                  );
                }
              }
            },
            icon: const Icon(Icons.check_rounded, size: 18),
            label: const Text('Generate Now'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final budgetState = ref.watch(budgetProvider);
    final txState = ref.watch(transactionProvider);
    final isDark = Theme.of(context).brightness == Brightness.dark;

    final income = txState.cashFlowSummary['income'] ?? 0.0;
    final refPool = income > 0 ? income : (budgetState.totalBudgeted > 0 ? budgetState.totalBudgeted : 3000.0);

    final strategy = budgetState.activeStrategy;
    final compliance = budgetState.computeStrategyCompliance(referenceMonthlyIncome: income);

    final targetPcts = BudgetStrategyHelper.getStrategyTargetPercentages(
      strategy,
      customPercentages: budgetState.customStrategyPercentages,
    );

    final spent = budgetState.bucketSpent;
    final budgeted = budgetState.bucketBudgeted;

    Color complianceColor;
    String complianceLabel;
    if (compliance >= 85) {
      complianceColor = AppColors.income;
      complianceLabel = 'Excellent Adherence';
    } else if (compliance >= 65) {
      complianceColor = AppColors.primary;
      complianceLabel = 'Good Balance';
    } else if (compliance >= 45) {
      complianceColor = AppColors.warning;
      complianceLabel = 'Needs Attention';
    } else {
      complianceColor = AppColors.error;
      complianceLabel = 'Off Track';
    }

    return Card(
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Padding(
        padding: const EdgeInsets.all(18),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Strategy Selector Header
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        color: AppColors.primary.withAlpha(25),
                        borderRadius: BorderRadius.circular(10),
                      ),
                      child: const Icon(Icons.pie_chart_rounded, color: AppColors.primary, size: 22),
                    ),
                    const SizedBox(width: 10),
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'Budgeting Strategy',
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                        ),
                        Text(
                          strategy.displayName,
                          style: const TextStyle(fontSize: 12, color: AppColors.primary, fontWeight: FontWeight.bold),
                        ),
                      ],
                    ),
                  ],
                ),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: complianceColor.withAlpha(25),
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(color: complianceColor.withAlpha(80)),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.shield_rounded, size: 14, color: complianceColor),
                      const SizedBox(width: 4),
                      Text(
                        '${compliance.toStringAsFixed(0)}% $complianceLabel',
                        style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: complianceColor),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),

            Text(
              strategy.description,
              style: TextStyle(fontSize: 12, color: isDark ? Colors.grey[300] : Colors.grey[700]),
            ),
            const SizedBox(height: 14),

            // Segmented Strategy Switcher Chips
            SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Row(
                children: BudgetStrategyType.values.map((s) {
                  final isSelected = s == strategy;
                  return Padding(
                    padding: const EdgeInsets.only(right: 8),
                    child: ChoiceChip(
                      label: Text(s.shortName),
                      selected: isSelected,
                      selectedColor: AppColors.primary.withAlpha(40),
                      labelStyle: TextStyle(
                        fontSize: 12,
                        fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                        color: isSelected ? AppColors.primary : null,
                      ),
                      onSelected: (_) {
                        ref.read(budgetProvider.notifier).setStrategy(s);
                      },
                    ),
                  );
                }).toList(),
              ),
            ),
            const SizedBox(height: 16),
            const Divider(height: 1),
            const SizedBox(height: 16),

            // 3 Buckets Breakdown: Needs, Wants, Savings/Debt
            _buildBucketProgressRow(
              context: context,
              bucket: BudgetBucket.needs,
              targetPct: targetPcts[BudgetBucket.needs] ?? 50.0,
              targetAmount: refPool * ((targetPcts[BudgetBucket.needs] ?? 50.0) / 100),
              actualSpent: spent[BudgetBucket.needs] ?? 0.0,
              budgetedAmount: budgeted[BudgetBucket.needs] ?? 0.0,
              color: AppColors.primary,
              curr: currency,
            ),
            const SizedBox(height: 12),
            _buildBucketProgressRow(
              context: context,
              bucket: BudgetBucket.wants,
              targetPct: targetPcts[BudgetBucket.wants] ?? 30.0,
              targetAmount: refPool * ((targetPcts[BudgetBucket.wants] ?? 30.0) / 100),
              actualSpent: spent[BudgetBucket.wants] ?? 0.0,
              budgetedAmount: budgeted[BudgetBucket.wants] ?? 0.0,
              color: Colors.purple,
              curr: currency,
            ),
            const SizedBox(height: 12),
            _buildBucketProgressRow(
              context: context,
              bucket: BudgetBucket.savingsDebt,
              targetPct: targetPcts[BudgetBucket.savingsDebt] ?? 20.0,
              targetAmount: refPool * ((targetPcts[BudgetBucket.savingsDebt] ?? 20.0) / 100),
              actualSpent: spent[BudgetBucket.savingsDebt] ?? 0.0,
              budgetedAmount: budgeted[BudgetBucket.savingsDebt] ?? 0.0,
              color: AppColors.income,
              curr: currency,
            ),
            const SizedBox(height: 16),

            // Action Buttons
            Row(
              children: [
                Expanded(
                  child: OutlinedButton.icon(
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 10),
                      side: const BorderSide(color: AppColors.primary),
                    ),
                    onPressed: () => _showAutoGenerateDialog(context, ref, income),
                    icon: const Icon(Icons.auto_awesome_rounded, size: 16),
                    label: const Text('Auto-Generate from Strategy', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold)),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildBucketProgressRow({
    required BuildContext context,
    required BudgetBucket bucket,
    required double targetPct,
    required double targetAmount,
    required double actualSpent,
    required double budgetedAmount,
    required Color color,
    required String curr,
  }) {
    final progress = targetAmount > 0 ? (actualSpent / targetAmount).clamp(0.0, 1.5) : 0.0;
    final isOver = actualSpent > targetAmount && targetAmount > 0;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Row(
              children: [
                Container(
                  width: 8,
                  height: 8,
                  decoration: BoxDecoration(color: color, shape: BoxShape.circle),
                ),
                const SizedBox(width: 6),
                Text(
                  '${bucket.displayName} (${targetPct.toStringAsFixed(0)}%)',
                  style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w600),
                ),
              ],
            ),
            Text(
              '${CurrencyFormatter.format(actualSpent, symbol: curr)} / ${CurrencyFormatter.format(targetAmount, symbol: curr)}',
              style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.bold,
                color: isOver ? AppColors.error : null,
              ),
            ),
          ],
        ),
        const SizedBox(height: 6),
        ClipRRect(
          borderRadius: BorderRadius.circular(6),
          child: LinearProgressIndicator(
            value: progress > 1.0 ? 1.0 : progress,
            minHeight: 7,
            backgroundColor: Colors.grey.withAlpha(40),
            color: isOver ? AppColors.error : color,
          ),
        ),
      ],
    );
  }
}
