import 'package:uuid/uuid.dart';
import '../security/crypto_utils.dart';

class SeedData {
  SeedData._();

  static const _uuid = Uuid();

  static final List<Map<String, dynamic>> defaultCategories = [
    // Income Categories
    {
      'id': 'cat_inc_salary',
      'name': 'Salary',
      'type': 'income',
      'icon': 'work',
      'color': '0xFF10B981',
      'parent_id': null,
    },
    {
      'id': 'cat_inc_freelance',
      'name': 'Freelancing / Business',
      'type': 'income',
      'icon': 'laptop',
      'color': '0xFF3B82F6',
      'parent_id': null,
    },
    {
      'id': 'cat_inc_investment',
      'name': 'Investment & Dividends',
      'type': 'income',
      'icon': 'trending_up',
      'color': '0xFF8B5CF6',
      'parent_id': null,
    },
    {
      'id': 'cat_inc_rental',
      'name': 'Rental Income',
      'type': 'income',
      'icon': 'home',
      'color': '0xFF06B6D4',
      'parent_id': null,
    },
    {
      'id': 'cat_inc_cashback',
      'name': 'Cashback & Rewards',
      'type': 'income',
      'icon': 'card_giftcard',
      'color': '0xFFF59E0B',
      'parent_id': null,
    },
    {
      'id': 'cat_inc_other',
      'name': 'Other Income',
      'type': 'income',
      'icon': 'attach_money',
      'color': '0xFF14B8A6',
      'parent_id': null,
    },

    // Expense Categories
    {
      'id': 'cat_exp_food',
      'name': 'Food & Dining',
      'type': 'expense',
      'icon': 'restaurant',
      'color': '0xFFF43F5E',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_groceries',
      'name': 'Groceries',
      'type': 'expense',
      'icon': 'shopping_cart',
      'color': '0xFFF97316',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_rent',
      'name': 'Housing & Rent',
      'type': 'expense',
      'icon': 'apartment',
      'color': '0xFFEC4899',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_utilities',
      'name': 'Utilities & Bills',
      'type': 'expense',
      'icon': 'bolt',
      'color': '0xFFEAB308',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_transport',
      'name': 'Transport & Fuel',
      'type': 'expense',
      'icon': 'directions_car',
      'color': '0xFF06B6D4',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_shopping',
      'name': 'Shopping',
      'type': 'expense',
      'icon': 'shopping_bag',
      'color': '0xFF8B5CF6',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_healthcare',
      'name': 'Healthcare & Medical',
      'type': 'expense',
      'icon': 'medical_services',
      'color': '0xFFEF4444',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_entertainment',
      'name': 'Entertainment & Leisure',
      'type': 'expense',
      'icon': 'movie',
      'color': '0xFFA855F7',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_subscriptions',
      'name': 'Subscriptions',
      'type': 'expense',
      'icon': 'subscriptions',
      'color': '0xFF6366F1',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_emi',
      'name': 'Loans & EMIs',
      'type': 'expense',
      'icon': 'account_balance',
      'color': '0xFFF59E0B',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_education',
      'name': 'Education',
      'type': 'expense',
      'icon': 'school',
      'color': '0xFF3B82F6',
      'parent_id': null,
    },
    {
      'id': 'cat_exp_other',
      'name': 'Other Expense',
      'type': 'expense',
      'icon': 'receipt_long',
      'color': '0xFF64748B',
      'parent_id': null,
    },

    // Transfer Category
    {
      'id': 'cat_transfer_general',
      'name': 'Account Transfer',
      'type': 'transfer',
      'icon': 'swap_horiz',
      'color': '0xFF6366F1',
      'parent_id': null,
    },
  ];

  static final List<Map<String, dynamic>> defaultAccounts = [
    {
      'id': 'acc_demo_savings',
      'user_id': 'usr_demo_primary',
      'account_token': 'tok_acc_savings_demo_primary',
      'name': 'Salary & Savings Bank',
      'type': 'Bank Account',
      'institution': 'HDFC Bank',
      'masked_reference': '•••• 1024',
      'opening_balance': 45000.0,
      'current_balance': 45000.0,
      'currency': 'INR',
      'status': 'active',
      'credit_limit': 0.0,
      'interest_rate': 3.5,
      'opened_at': DateTime.now().subtract(const Duration(days: 90)).toIso8601String(),
      'notes': 'Primary salary account',
      'is_deleted': 0,
    },
    {
      'id': 'acc_demo_cash',
      'user_id': 'usr_demo_primary',
      'account_token': 'tok_acc_cash_demo_primary',
      'name': 'Cash Wallet',
      'type': 'Cash',
      'institution': 'Physical Cash',
      'masked_reference': null,
      'opening_balance': 5500.0,
      'current_balance': 5500.0,
      'currency': 'INR',
      'status': 'active',
      'credit_limit': 0.0,
      'interest_rate': 0.0,
      'opened_at': DateTime.now().subtract(const Duration(days: 90)).toIso8601String(),
      'notes': 'Physical cash wallet',
      'is_deleted': 0,
    },
    {
      'id': 'acc_demo_credit_card',
      'user_id': 'usr_demo_primary',
      'account_token': 'tok_acc_credit_demo_primary',
      'name': 'Platinum Credit Card',
      'type': 'Credit Card',
      'institution': 'ICICI Bank',
      'masked_reference': '•••• 8892',
      'opening_balance': 0.0,
      'current_balance': -8450.0, // Outstanding liability
      'currency': 'INR',
      'status': 'active',
      'credit_limit': 150000.0,
      'interest_rate': 42.0,
      'opened_at': DateTime.now().subtract(const Duration(days: 120)).toIso8601String(),
      'notes': 'Billing date: 15th each month',
      'is_deleted': 0,
    },
    {
      'id': 'acc_demo_fd',
      'user_id': 'usr_demo_primary',
      'account_token': 'tok_acc_fd_demo_primary',
      'name': 'Emergency Fixed Deposit',
      'type': 'Fixed Deposit',
      'institution': 'SBI',
      'masked_reference': '•••• 5541',
      'opening_balance': 100000.0,
      'current_balance': 100000.0,
      'currency': 'INR',
      'status': 'active',
      'credit_limit': 0.0,
      'interest_rate': 7.1,
      'opened_at': DateTime.now().subtract(const Duration(days: 60)).toIso8601String(),
      'notes': 'Maturity: 1 Year',
      'is_deleted': 0,
    },
  ];

  static List<Map<String, dynamic>> generateDemoTransactions() {
    final now = DateTime.now();
    return [
      {
        'id': _uuid.v4(),
        'source_account_id': 'acc_demo_savings',
        'destination_account_id': null,
        'type': 'income',
        'category_id': 'cat_inc_salary',
        'amount': 85000.0,
        'date': now.subtract(const Duration(days: 9)).toIso8601String(),
        'description': 'Monthly Salary Deposit',
        'payee_payer': 'Employer Tech Corp',
        'payment_method': 'Bank Transfer / NEFT',
        'reference_number': 'SAL-SEP-001',
        'status': 'completed',
        'is_recurring_instance_of': null,
        'notes': 'Net salary after TDS',
        'is_reconciled': 1,
        'created_at': now.toIso8601String(),
        'updated_at': now.toIso8601String(),
        'is_deleted': 0,
      },
      {
        'id': _uuid.v4(),
        'source_account_id': 'acc_demo_savings',
        'destination_account_id': null,
        'type': 'expense',
        'category_id': 'cat_exp_rent',
        'amount': 22000.0,
        'date': now.subtract(const Duration(days: 8)).toIso8601String(),
        'description': 'Apartment Monthly Rent',
        'payee_payer': 'Landlord Sharma',
        'payment_method': 'UPI',
        'reference_number': 'UPI/3882910',
        'status': 'completed',
        'is_recurring_instance_of': null,
        'notes': 'Monthly rent for flat',
        'is_reconciled': 1,
        'created_at': now.toIso8601String(),
        'updated_at': now.toIso8601String(),
        'is_deleted': 0,
      },
      {
        'id': _uuid.v4(),
        'source_account_id': 'acc_demo_savings',
        'destination_account_id': 'acc_demo_cash',
        'type': 'transfer',
        'category_id': 'cat_transfer_general',
        'amount': 5000.0,
        'date': now.subtract(const Duration(days: 6)).toIso8601String(),
        'description': 'ATM Cash Withdrawal',
        'payee_payer': 'ATM Withdrawal',
        'payment_method': 'Debit Card',
        'reference_number': 'ATM-901',
        'status': 'completed',
        'is_recurring_instance_of': null,
        'notes': 'Withdrawn for petty expenses',
        'is_reconciled': 1,
        'created_at': now.toIso8601String(),
        'updated_at': now.toIso8601String(),
        'is_deleted': 0,
      },
      {
        'id': _uuid.v4(),
        'source_account_id': 'acc_demo_credit_card',
        'destination_account_id': null,
        'type': 'expense',
        'category_id': 'cat_exp_groceries',
        'amount': 4250.0,
        'date': now.subtract(const Duration(days: 4)).toIso8601String(),
        'description': 'Supermarket Groceries',
        'payee_payer': 'Nature Basket',
        'payment_method': 'Credit Card',
        'reference_number': 'POS-88219',
        'status': 'completed',
        'is_recurring_instance_of': null,
        'notes': 'Monthly pantry restock',
        'is_reconciled': 0,
        'created_at': now.toIso8601String(),
        'updated_at': now.toIso8601String(),
        'is_deleted': 0,
      },
      {
        'id': _uuid.v4(),
        'source_account_id': 'acc_demo_credit_card',
        'destination_account_id': null,
        'type': 'expense',
        'category_id': 'cat_exp_food',
        'amount': 1800.0,
        'date': now.subtract(const Duration(days: 2)).toIso8601String(),
        'description': 'Weekend Dining',
        'payee_payer': 'The Olive Bistro',
        'payment_method': 'Credit Card',
        'reference_number': 'POS-9120',
        'status': 'completed',
        'is_recurring_instance_of': null,
        'notes': 'Dinner with friends',
        'is_reconciled': 0,
        'created_at': now.toIso8601String(),
        'updated_at': now.toIso8601String(),
        'is_deleted': 0,
      },
      {
        'id': _uuid.v4(),
        'source_account_id': 'acc_demo_savings',
        'destination_account_id': null,
        'type': 'expense',
        'category_id': 'cat_exp_utilities',
        'amount': 2400.0,
        'date': now.subtract(const Duration(days: 1)).toIso8601String(),
        'description': 'Electricity & High-speed Fiber',
        'payee_payer': 'Power & Internet Corp',
        'payment_method': 'UPI',
        'reference_number': 'BILL-8271',
        'status': 'completed',
        'is_recurring_instance_of': null,
        'notes': 'Auto-debited utility bill',
        'is_reconciled': 1,
        'created_at': now.toIso8601String(),
        'updated_at': now.toIso8601String(),
        'is_deleted': 0,
      },
    ];
  }

  static Map<String, dynamic> getDefaultDemoUser() {
    const salt = 's4lt_d3m0_2026';
    final hash = CryptoUtils.hashPassword('demo123', salt);
    final now = DateTime.now().toIso8601String();
    return {
      'id': 'usr_demo_primary',
      'email': 'demo@personalfinance.local',
      'username': 'demouser',
      'full_name': 'Alex Johnson',
      'password_hash': hash,
      'salt': salt,
      'reset_token': null,
      'reset_token_expiry': null,
      'created_at': now,
      'updated_at': now,
    };
  }
}
